[book]
title = "Official Rankup Wiki"
authors = ["okx-code", "NicBOMB", "flurbudurbur"]
language = "en"
description = "Official Rankup wiki."
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/okx-code/Rankup3"
input-404 = "Error.md"
site-url = "/rankup/"

[output.html.print]
enable = false

[output.html.redirect]
"/Core-Files/Config-Placeholders.html" = "/rankup/Config-Placeholders.html"
"/Core-Files/FAQ.html" = "/rankup/FAQ.html"
"/Core-Files/For-Developers.html" = "/rankup/For-Developers.html"
"/Core-Files/Home.html" = "/rankup/Home.html"
"/Core-Files/List-of-Requirements.html" = "/rankup/List-of-Requirements.html"
"/Core-Files/PAPI-Placeholders.html" = "/rankup/PAPI-Placeholders.html"
"/Core-Files/Rankups-and-Prestiges.html" = "/rankup/Rankups-and-Prestiges.html"
"/Core-Files/Rankups-and-prestiges.html" = "/rankup/Rankups-and-Prestiges.html"
"/Core-Files/Text-Templating.html" = "/rankup/Text-Templating.html"
"/Discord/Okx-Corner.html" = "https://discord.gg/zbkbhBj"
"/GitHub/McMMO/DesignDoc.html" = "https://docs.google.com/document/d/1qY6hEyGCO5z1PRup_OvMBxAmumydxxoO_H-pnUrVK8M/edit#heading=h.nhed81k1qlj7"
"/GitHub/McMMO/CorePrimarySkillTypes.html" = "https://github.com/mcMMO-Dev/mcMMO-API/blob/master/src/main/java/com/neetgames/mcmmo/skill/CorePrimarySkillType.java"
"/GitHub/Rankup3/config.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml"
"/GitHub/Rankup3/config/AutoRankup-Interval.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L10-L13"
"/GitHub/Rankup3/config/DisplayName.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L96"
"/GitHub/Rankup3/config/Ranks.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L15-L18"
"/GitHub/Rankup3/config/Prestiges.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L19-L21"
"/GitHub/Rankup3/config/Prestige.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L27-L35"
"/GitHub/Rankup3/config/MaxRankup.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L61-L68"
"/GitHub/Rankup3/config/RanksGUI.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L23-L25"
"/GitHub/Rankup3/config/Permission-Rankup.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L41-L47"
"/GitHub/Rankup3/config/ConfirmationGUI.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L49-L51"
"/GitHub/Rankup3/config/Cooldown.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L53-L55"
"/GitHub/Rankup3/config/Status.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L92-L95"
"/GitHub/Rankup3/DeductibleRequirementCode.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/requirements/DeductibleRequirement.java"
"/GitHub/Rankup3/locale.html" = "https://github.com/okx-code/Rankup3/tree/master/src/main/resources/locale"
"/GitHub/Rankup3/locale/en.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/locale/en.yml"
"/GitHub/Rankup3/locale/en/RanksGUI.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/locale/en.yml#L38-L54"
"/GitHub/Rankup3/prestiges.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/prestiges.yml"
"/GitHub/Rankup3/Java/ProgressiveRequirementCode.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/requirements/ProgressiveRequirement.java"
"/GitHub/Rankup3/Java/RankListCode.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/ranks/RankList.java"
"/GitHub/Rankup3/Java/RankupPlugin.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/RankupPlugin.java"
"/GitHub/Rankup3/Java/Reload.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/RankupPlugin.java#L190-L233"
"/GitHub/Rankup3/Java/EnableRankupPlugin.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/RankupPlugin.java#L127"
"/GitHub/Rankup3/Java/commands/InfoCommand.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java"
"/GitHub/Rankup3/Java/commands/InfoCommand/playtime-get.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L204"
"/GitHub/Rankup3/Java/commands/InfoCommand/playtime-set.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L244"
"/GitHub/Rankup3/Java/commands/InfoCommand/playtime-add.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L267"
"/GitHub/Rankup3/Java/commands/InfoCommand/checkversion.html" = "https://github.com/okx-code/Rankup3/blob/59e97d3f61608ee0495047fd4ebf4dc13b09008d/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L340-L342"
"/GitHub/Rankup3/Java/commands/InfoCommand/forcerankup.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L46"
"/GitHub/Rankup3/Java/commands/InfoCommand/forceprestige.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L77"
"/GitHub/Rankup3/Java/commands/InfoCommand/placeholders.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L161"
"/GitHub/Rankup3/Java/commands/InfoCommand/tree.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L194"
"/GitHub/Rankup3/Java/commands/InfoCommand/rankdown.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L116"
"/GitHub/Rankup3/Java/commands/InfoCommand/reload.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/InfoCommand.java#L40-L45"
"/GitHub/Rankup3/Java/commands/MaxRankupCommand.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/MaxRankupCommand.java"
"/GitHub/Rankup3/Java/commands/PrestigeCommand.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/PrestigeCommand.java"
"/GitHub/Rankup3/Java/commands/PrestigesCommand.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/PrestigesCommand.java"
"/GitHub/Rankup3/Java/commands/RanksCommand.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/RanksCommand.java"
"/GitHub/Rankup3/Java/commands/RankupCommand.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/commands/RankupCommand.java"
"/GitHub/Rankup3/Java/RankRegisterEventCode.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/java/sh/okx/rankup/events/RankupRegisterEvent.java"
"/GitHub/Rankup3/rankups.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/rankups.yml"
"/GitHub/Rankup3/rankups/rank.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/rankups.yml#L12"
"/GitHub/Rankup3/rankups/next.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/rankups.yml#L14"
"/GitHub/Rankup3/plugin/Admin.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/plugin.yml#L39-L50"
"/GitHub/Rankup3/plugin/Auto-Rankup.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/plugin.yml#L59-L60"
"/GitHub/Rankup3/plugin/force.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/plugin.yml#L45-L46"
"/GitHub/Rankup3/plugin/Player.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/plugin.yml#L51-L70"
"/GitHub/Rankup3/plugin/PRU.html" = "https://github.com/okx-code/Rankup3/blob/master/src/main/resources/plugin.yml#L13-L16"
"/GitHub/Rankup3/resources.html" = "https://github.com/okx-code/Rankup3/tree/master/src/main/resources"
"/GitHub/Paper/website.html" = "https://papermc.io/"
"/GitHub/PAPI/Placeholders.html" = "https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders"
"/GitHub/PAPI/Progress.html" = "https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#progress"
"/GitHub/Progress-Expansion.html" = "https://github.com/aBooDyy/Progress-Expansion"
"/GitHub/Progress-Examples.html" = "https://github.com/aBooDyy/Progress-Expansion#m"
"/Jenkins/Rankup3.html" = "https://ci.okx.sh/job/Rankup3/"
"/LuckPerms/Wiki/General-Commands/creategroup.html" = "https://luckperms.net/wiki/General-Commands#lp-creategroup-name-weight-displayname"
"/LuckPerms/Wiki/Default-Assignments-Extension.html" = "https://luckperms.net/wiki/Extensions#extension-default-assignments"
"/LuckPerms/Wiki/Default-Groups/Default-Assignments.html" = "https://luckperms.net/wiki/Default-Groups#configure-default-assignments"
"/LuckPerms/Wiki/Migration.html" = "https://luckperms.net/wiki/Migration"
"/Minecraft/Wiki/Flattening.html" = "https://minecraft.fandom.com/wiki/Java_Edition_1.13/Flattening#Block_and_item_IDs"
"/Minecraft/Wiki/Advancements.html" = "https://minecraft.fandom.com/wiki/Advancement#List_of_advancements"
"/Pebble/templates.html" = "https://pebbletemplates.io/"
"/Pebble/Basic-Usage.html" = "https://pebbletemplates.io/wiki/guide/basic-usage/#syntax-reference"
"/Pebble/filters.html" = "https://pebbletemplates.io/wiki/filter/abbreviate/"
"/Pebble/Math.html" = "https://pebbletemplates.io/wiki/operator/math/"
"/Pebble/For.html" = "https://pebbletemplates.io/wiki/tag/for/"
"/Pebble/If.html" = "https://pebbletemplates.io/wiki/tag/if/"
"/Pebble/Iterable.html" = "https://pebbletemplates.io/wiki/test/iterable/"
"/Pebble/Comparisons.html" = "https://pebbletemplates.io/wiki/operator/comparisons/"
"/Pebble/Logic.html" = "https://pebbletemplates.io/wiki/operator/logic/"
"/Pebble/Set.html" = "https://pebbletemplates.io/wiki/tag/set/"
"/Pebble/Ternary.html" = "https://pebbletemplates.io/wiki/operator/others/"
"/Spigot/deprecated.html" = "https://www.spigotmc.org/resources/rankup.17933/"
"/Spigot/LuckPerms.html" = "https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/"
"/Spigot/website.html" = "https://www.spigotmc.org/"
"/Spigot/rankup3.html" = "https://www.spigotmc.org/resources/rankup.76964/"
"/Spigot/PAPI.html" = "https://www.spigotmc.org/resources/placeholderapi.6245/"
"/Spigot/TokenManager.html" = "https://www.spigotmc.org/resources/tokenmanager.8610/"
"/Spigot/Docs/entity.html" = "https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/package-summary.html"
"/Spigot/Docs/materials.html" = "https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html"
"/Spigot/Docs/mobs.html" = "https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html"
"/Validators/CodeBeautify.html" = "https://codebeautify.org/yaml-validator"
"/Validators/Multiline.html" = "https://yaml-multiline.info/"
